#!/usr/bin/env python3
"""
Update Supabase database with Cloudflare Images IDs.

This script reads the upload_log.csv generated by upload_cloudflare.py
and updates the Supabase database with the corresponding Cloudflare image IDs.

Usage:
    python scripts/update_image_ids.py <upload_log.csv> [--supabase-url URL] [--supabase-key KEY]

Environment variables (alternative to CLI args):
    SUPABASE_URL: Your Supabase project URL
    SUPABASE_SERVICE_KEY: Your Supabase service role key (for writes)

Example:
    python scripts/update_image_ids.py scripts/upload_log.csv

Output:
    Updates the cloudflare_image_id column in the images table
"""

import argparse
import csv
import os
import sys
from pathlib import Path

try:
    from supabase import create_client, Client
except ImportError:
    print("Error: supabase-py not installed. Run: pip install supabase")
    sys.exit(1)


def parse_upload_log(log_file: Path) -> dict:
    """
    Parse upload_log.csv and return mapping of file paths to Cloudflare IDs.
    
    Args:
        log_file: Path to upload_log.csv
        
    Returns:
        Dict mapping file_path -> cloudflare_image_id
    """
    mapping = {}
    
    with open(log_file, 'r') as f:
        reader = csv.DictReader(f)
        for row in reader:
            if row['status'] == 'SUCCESS' and row['image_id']:
                # Extract just the filename from the path (e.g., "c1/photo.jpg" -> "c1/photo.jpg")
                file_path = row['file']
                mapping[file_path] = row['image_id']
    
    return mapping


def update_supabase(client: Client, file_to_cf_id: dict, dry_run: bool = False):
    """
    Update Supabase images table with Cloudflare image IDs.
    
    Args:
        client: Supabase client
        file_to_cf_id: Mapping of file paths to Cloudflare IDs
        dry_run: If True, don't actually update, just print what would be done
    """
    # Get all images from Supabase
    print("Fetching images from Supabase...")
    response = client.table('images').select('id, file_path, thumbnail').execute()
    images = response.data
    print(f"Found {len(images)} images in database")
    
    updated = 0
    not_found = 0
    
    for img in images:
        file_path = img['file_path']
        thumbnail = img.get('thumbnail')
        
        # Try to match with uploaded files
        # The upload log has paths like "caves_1200px/c1/photo.jpg"
        # The database has paths like "c1/photo.jpg"
        
        cf_image_id = None
        cf_thumbnail_id = None
        
        # Look for main image
        for log_path, cf_id in file_to_cf_id.items():
            if log_path.endswith(file_path) or f"caves_1200px/{file_path}" == log_path:
                cf_image_id = cf_id
                break
        
        # Look for thumbnail
        if thumbnail:
            for log_path, cf_id in file_to_cf_id.items():
                if log_path.endswith(thumbnail) or f"caves_thumbs/{thumbnail}" == log_path:
                    cf_thumbnail_id = cf_id
                    break
        
        if cf_image_id:
            if dry_run:
                print(f"Would update image {img['id']}: {file_path} -> {cf_image_id}")
            else:
                update_data = {'cloudflare_image_id': cf_image_id}
                if cf_thumbnail_id:
                    update_data['cloudflare_thumbnail_id'] = cf_thumbnail_id
                
                client.table('images').update(update_data).eq('id', img['id']).execute()
            updated += 1
        else:
            not_found += 1
            if not_found <= 10:  # Only show first 10 missing
                print(f"Warning: No Cloudflare ID found for: {file_path}")
    
    print(f"\nResults:")
    print(f"  Updated: {updated}")
    print(f"  Not found: {not_found}")
    
    if not_found > 10:
        print(f"  (Showing first 10 not-found warnings)")


def main():
    parser = argparse.ArgumentParser(
        description="Update Supabase with Cloudflare Image IDs",
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument("upload_log", type=Path, help="Path to upload_log.csv")
    parser.add_argument("--supabase-url", help="Supabase project URL")
    parser.add_argument("--supabase-key", help="Supabase service role key")
    parser.add_argument("--dry-run", action="store_true", help="Don't update, just show what would be done")
    
    args = parser.parse_args()
    
    # Get Supabase credentials
    supabase_url = args.supabase_url or os.getenv("SUPABASE_URL")
    supabase_key = args.supabase_key or os.getenv("SUPABASE_SERVICE_KEY")
    
    if not supabase_url or not supabase_key:
        print("Error: Supabase credentials required.")
        print("Set SUPABASE_URL and SUPABASE_SERVICE_KEY environment variables")
        print("Or use --supabase-url and --supabase-key arguments")
        sys.exit(1)
    
    if not args.upload_log.exists():
        print(f"Error: File not found: {args.upload_log}")
        sys.exit(1)
    
    # Parse upload log
    print(f"Reading upload log: {args.upload_log}")
    file_to_cf_id = parse_upload_log(args.upload_log)
    print(f"Found {len(file_to_cf_id)} successful uploads")
    
    if not file_to_cf_id:
        print("No successful uploads found in log")
        sys.exit(0)
    
    # Connect to Supabase
    print(f"\nConnecting to Supabase: {supabase_url}")
    client = create_client(supabase_url, supabase_key)
    
    # Update database
    update_supabase(client, file_to_cf_id, dry_run=args.dry_run)
    
    print("\n✅ Done!")


if __name__ == "__main__":
    main()

