-- Undo deduplication: re-insert deleted records
-- Generated: 2026-03-07T21:55:13.837479+00:00
-- Run this to restore deleted records (CF images must be re-uploaded separately)

BEGIN;

INSERT INTO images (image_id, cave_id, plan_id, file_path, rank, best_id, cloudflare_image_id, cloudflare_thumbnail_id, book_figure, book_page, plan_x_norm, plan_y_norm, subject, description, motifs, medium, photographer, default_priority, hide_plan_xy, thumbnail) VALUES (8214, 15, 15, 'c15/DSCN4671.jpg', 1, NULL, '5177654c-5077-4e32-2b70-2b2f07b79900', NULL, NULL, NULL, NULL, NULL, '', '', '', 'photograph', 'Arno Klein', 0, FALSE, NULL) ON CONFLICT (image_id) DO NOTHING;
INSERT INTO images (image_id, cave_id, plan_id, file_path, rank, best_id, cloudflare_image_id, cloudflare_thumbnail_id, book_figure, book_page, plan_x_norm, plan_y_norm, subject, description, motifs, medium, photographer, default_priority, hide_plan_xy, thumbnail) VALUES (4382, 9, 9, 'c9/c9F1.jpg', 1, 4376, 'd3850575-56c3-43ea-3c83-f85891cfc700', NULL, NULL, NULL, 0.49375, 0.56122449, 'Facada', 'Cave 9''s elaborate upper facade levels contain a series of six seated Buddhas in ornate arches, in a sequence of three, two, and one, reading from bottom to top. Playful dwarfs and supporting yakshas appear between the arches, while bhadrasana Buddhas, probably the ""Seven Historical Buddhas", alternate with standing bodhisattvas, in the frieze below.', 'Facade', 'rock-cut', 'Arno Klein', 0, FALSE, NULL) ON CONFLICT (image_id) DO NOTHING;
INSERT INTO images (image_id, cave_id, plan_id, file_path, rank, best_id, cloudflare_image_id, cloudflare_thumbnail_id, book_figure, book_page, plan_x_norm, plan_y_norm, subject, description, motifs, medium, photographer, default_priority, hide_plan_xy, thumbnail) VALUES (8735, 4, 4, 'c1-9/DSCN4325.jpg', 1, NULL, '193ffb32-76d5-4583-7eba-d2bb06a58d00', NULL, NULL, NULL, NULL, NULL, '', '', '', 'photograph', 'Arno Klein', 0, FALSE, NULL) ON CONFLICT (image_id) DO NOTHING;
INSERT INTO images (image_id, cave_id, plan_id, file_path, rank, best_id, cloudflare_image_id, cloudflare_thumbnail_id, book_figure, book_page, plan_x_norm, plan_y_norm, subject, description, motifs, medium, photographer, default_priority, hide_plan_xy, thumbnail) VALUES (7531, 4, 4, 'Ellora c1-7 copy_PXL_20230310_015200592.dng.jpg', 2, 7532, '07ca1c5b-1b76-4be5-5293-054191ddd100', NULL, NULL, NULL, NULL, NULL, '', '', '', 'photograph', 'Arno Klein', 0, FALSE, NULL) ON CONFLICT (image_id) DO NOTHING;
INSERT INTO images (image_id, cave_id, plan_id, file_path, rank, best_id, cloudflare_image_id, cloudflare_thumbnail_id, book_figure, book_page, plan_x_norm, plan_y_norm, subject, description, motifs, medium, photographer, default_priority, hide_plan_xy, thumbnail) VALUES (7534, 7, 7, 'Ellora c1-7_PXL_20230310_015830927.dng.jpg', 2, 7543, '024c40a5-d8ff-4ce1-e2b5-550fa0eee200', NULL, NULL, NULL, NULL, NULL, '', '', '', 'photograph', 'Arno Klein', 0, FALSE, NULL) ON CONFLICT (image_id) DO NOTHING;
INSERT INTO images (image_id, cave_id, plan_id, file_path, rank, best_id, cloudflare_image_id, cloudflare_thumbnail_id, book_figure, book_page, plan_x_norm, plan_y_norm, subject, description, motifs, medium, photographer, default_priority, hide_plan_xy, thumbnail) VALUES (7535, 4, 4, 'Ellora c1-7 copy_PXL_20230310_014901708.dng.jpg', 1, 7532, 'b77ea233-07b4-4f96-50fd-13b493e48a00', NULL, NULL, NULL, NULL, NULL, '', '', '', 'photograph', 'Arno Klein', 0, FALSE, NULL) ON CONFLICT (image_id) DO NOTHING;
INSERT INTO images (image_id, cave_id, plan_id, file_path, rank, best_id, cloudflare_image_id, cloudflare_thumbnail_id, book_figure, book_page, plan_x_norm, plan_y_norm, subject, description, motifs, medium, photographer, default_priority, hide_plan_xy, thumbnail) VALUES (7543, 5, 5, 'Ellora c1-7 copy_PXL_20230310_015906720.dng.jpg', 2, NULL, '5bbbb28b-cdb8-45d3-7bd5-6d8c96778c00', NULL, NULL, NULL, NULL, NULL, '', '', '', 'photograph', 'Arno Klein', 0, FALSE, NULL) ON CONFLICT (image_id) DO NOTHING;
INSERT INTO images (image_id, cave_id, plan_id, file_path, rank, best_id, cloudflare_image_id, cloudflare_thumbnail_id, book_figure, book_page, plan_x_norm, plan_y_norm, subject, description, motifs, medium, photographer, default_priority, hide_plan_xy, thumbnail) VALUES (7544, 5, 5, 'Ellora c1-7 copy_PXL_20230310_015853321.dng.jpg', 2, 7543, '9e01a562-e832-4135-a274-ea136967e200', NULL, NULL, NULL, NULL, NULL, '', '', '', 'photograph', 'Arno Klein', 0, FALSE, NULL) ON CONFLICT (image_id) DO NOTHING;
INSERT INTO images (image_id, cave_id, plan_id, file_path, rank, best_id, cloudflare_image_id, cloudflare_thumbnail_id, book_figure, book_page, plan_x_norm, plan_y_norm, subject, description, motifs, medium, photographer, default_priority, hide_plan_xy, thumbnail) VALUES (7546, 4, 5, 'Ellora c1-7_PXL_20230310_020613864.dng.jpg', 2, 8735, '99f62525-6b6f-403b-0de5-12c1488a9d00', NULL, NULL, NULL, NULL, NULL, '', '', '', 'photograph', 'Arno Klein', 0, FALSE, NULL) ON CONFLICT (image_id) DO NOTHING;
INSERT INTO images (image_id, cave_id, plan_id, file_path, rank, best_id, cloudflare_image_id, cloudflare_thumbnail_id, book_figure, book_page, plan_x_norm, plan_y_norm, subject, description, motifs, medium, photographer, default_priority, hide_plan_xy, thumbnail) VALUES (7553, 23, 23, 'c23/c23BS_trimurti.jpg', 1, NULL, 'afa282a3-209b-4ce5-fb92-7cde0c290100', NULL, NULL, NULL, NULL, NULL, '', '', '', 'photograph', 'Arno Klein', 0, FALSE, NULL) ON CONFLICT (image_id) DO NOTHING;
INSERT INTO images (image_id, cave_id, plan_id, file_path, rank, best_id, cloudflare_image_id, cloudflare_thumbnail_id, book_figure, book_page, plan_x_norm, plan_y_norm, subject, description, motifs, medium, photographer, default_priority, hide_plan_xy, thumbnail) VALUES (7554, 23, 23, 'c23/c23BS_linga.jpg', 1, NULL, '71cc8168-44e2-4835-a1ee-b426af7e7400', NULL, NULL, NULL, NULL, NULL, '', '', '', 'photograph', 'Arno Klein', 0, FALSE, NULL) ON CONFLICT (image_id) DO NOTHING;
INSERT INTO images (image_id, cave_id, plan_id, file_path, rank, best_id, cloudflare_image_id, cloudflare_thumbnail_id, book_figure, book_page, plan_x_norm, plan_y_norm, subject, description, motifs, medium, photographer, default_priority, hide_plan_xy, thumbnail) VALUES (7555, 23, 23, 'c23/c23BS_lakulisa.jpg', 1, NULL, '71058f7c-3dc8-478d-1630-c9de1b2cb900', NULL, NULL, NULL, NULL, NULL, '', '', '', 'photograph', 'Arno Klein', 0, FALSE, NULL) ON CONFLICT (image_id) DO NOTHING;
INSERT INTO images (image_id, cave_id, plan_id, file_path, rank, best_id, cloudflare_image_id, cloudflare_thumbnail_id, book_figure, book_page, plan_x_norm, plan_y_norm, subject, description, motifs, medium, photographer, default_priority, hide_plan_xy, thumbnail) VALUES (7556, 23, 23, 'c23/c23BSD.jpg', 1, NULL, '01b6ab43-d4fc-4f91-b9f0-acf456d93a00', NULL, NULL, NULL, NULL, NULL, '', '', '', 'photograph', 'Arno Klein', 0, FALSE, NULL) ON CONFLICT (image_id) DO NOTHING;
INSERT INTO images (image_id, cave_id, plan_id, file_path, rank, best_id, cloudflare_image_id, cloudflare_thumbnail_id, book_figure, book_page, plan_x_norm, plan_y_norm, subject, description, motifs, medium, photographer, default_priority, hide_plan_xy, thumbnail) VALUES (7557, 23, 23, 'c23/c23BHWr.jpg', 1, NULL, '4b2a7153-8535-4c55-6aa2-b4f6034c8000', NULL, NULL, NULL, NULL, NULL, '', '', '', 'photograph', 'Arno Klein', 0, FALSE, NULL) ON CONFLICT (image_id) DO NOTHING;
INSERT INTO images (image_id, cave_id, plan_id, file_path, rank, best_id, cloudflare_image_id, cloudflare_thumbnail_id, book_figure, book_page, plan_x_norm, plan_y_norm, subject, description, motifs, medium, photographer, default_priority, hide_plan_xy, thumbnail) VALUES (7558, 23, 23, 'c23/c23BHWbr_parvati.jpg', 1, NULL, '686931cf-162f-40d5-83c2-b0765d2b7800', NULL, NULL, NULL, NULL, NULL, '', '', '', 'photograph', 'Arno Klein', 0, FALSE, NULL) ON CONFLICT (image_id) DO NOTHING;
INSERT INTO images (image_id, cave_id, plan_id, file_path, rank, best_id, cloudflare_image_id, cloudflare_thumbnail_id, book_figure, book_page, plan_x_norm, plan_y_norm, subject, description, motifs, medium, photographer, default_priority, hide_plan_xy, thumbnail) VALUES (7559, 23, 23, 'c23/c23BHWbl_ganesa.jpg', 1, NULL, '81a6f6aa-6f6f-429f-f82d-bfc9963e1700', NULL, NULL, NULL, NULL, NULL, '', '', '', 'photograph', 'Arno Klein', 0, FALSE, NULL) ON CONFLICT (image_id) DO NOTHING;
INSERT INTO images (image_id, cave_id, plan_id, file_path, rank, best_id, cloudflare_image_id, cloudflare_thumbnail_id, book_figure, book_page, plan_x_norm, plan_y_norm, subject, description, motifs, medium, photographer, default_priority, hide_plan_xy, thumbnail) VALUES (7560, 23, 23, 'c23/c23B.jpg', 1, NULL, '30b11ac1-65ac-4802-578c-256905ee9400', NULL, NULL, NULL, NULL, NULL, '', '', '', 'photograph', 'Arno Klein', 0, FALSE, NULL) ON CONFLICT (image_id) DO NOTHING;
INSERT INTO images (image_id, cave_id, plan_id, file_path, rank, best_id, cloudflare_image_id, cloudflare_thumbnail_id, book_figure, book_page, plan_x_norm, plan_y_norm, subject, description, motifs, medium, photographer, default_priority, hide_plan_xy, thumbnail) VALUES (7561, 23, 23, 'c23/c23AWr_visnu2.jpg', 1, NULL, 'f0166287-2ca3-4e2e-1c5c-3946e3742b00', NULL, NULL, NULL, NULL, NULL, '', '', '', 'photograph', 'Arno Klein', 0, FALSE, NULL) ON CONFLICT (image_id) DO NOTHING;
INSERT INTO images (image_id, cave_id, plan_id, file_path, rank, best_id, cloudflare_image_id, cloudflare_thumbnail_id, book_figure, book_page, plan_x_norm, plan_y_norm, subject, description, motifs, medium, photographer, default_priority, hide_plan_xy, thumbnail) VALUES (7562, 23, 23, 'c23/c23AWr_visnu.jpg', 1, NULL, '542cc565-d496-48da-7477-741112a65700', NULL, NULL, NULL, NULL, NULL, '', '', '', 'photograph', 'Arno Klein', 0, FALSE, NULL) ON CONFLICT (image_id) DO NOTHING;
INSERT INTO images (image_id, cave_id, plan_id, file_path, rank, best_id, cloudflare_image_id, cloudflare_thumbnail_id, book_figure, book_page, plan_x_norm, plan_y_norm, subject, description, motifs, medium, photographer, default_priority, hide_plan_xy, thumbnail) VALUES (7563, 23, 23, 'c23/c23AWl_brahma.jpg', 1, NULL, '9f08385c-f0ae-46cd-8340-f4f04aa03900', NULL, NULL, NULL, NULL, NULL, '', '', '', 'photograph', 'Arno Klein', 0, FALSE, NULL) ON CONFLICT (image_id) DO NOTHING;
INSERT INTO images (image_id, cave_id, plan_id, file_path, rank, best_id, cloudflare_image_id, cloudflare_thumbnail_id, book_figure, book_page, plan_x_norm, plan_y_norm, subject, description, motifs, medium, photographer, default_priority, hide_plan_xy, thumbnail) VALUES (7564, 23, 23, 'c23/c23AS_linga.jpg', 1, NULL, 'd0c0e66c-a07d-497a-2c0c-162f31d0a200', NULL, NULL, NULL, NULL, NULL, '', '', '', 'photograph', 'Arno Klein', 0, FALSE, NULL) ON CONFLICT (image_id) DO NOTHING;
INSERT INTO images (image_id, cave_id, plan_id, file_path, rank, best_id, cloudflare_image_id, cloudflare_thumbnail_id, book_figure, book_page, plan_x_norm, plan_y_norm, subject, description, motifs, medium, photographer, default_priority, hide_plan_xy, thumbnail) VALUES (7565, 23, 23, 'c23/c23AS.jpg', 1, NULL, 'd4ea5504-0006-415a-cfb7-cb2a224cee00', NULL, NULL, NULL, NULL, NULL, '', '', '', 'photograph', 'Arno Klein', 0, FALSE, NULL) ON CONFLICT (image_id) DO NOTHING;
INSERT INTO images (image_id, cave_id, plan_id, file_path, rank, best_id, cloudflare_image_id, cloudflare_thumbnail_id, book_figure, book_page, plan_x_norm, plan_y_norm, subject, description, motifs, medium, photographer, default_priority, hide_plan_xy, thumbnail) VALUES (7566, 23, 23, 'c23/c23A.jpg', 1, NULL, '25d59932-6c29-4aec-ecdc-f8c741981d00', NULL, NULL, NULL, NULL, NULL, '', '', '', 'photograph', 'Arno Klein', 0, FALSE, NULL) ON CONFLICT (image_id) DO NOTHING;
INSERT INTO images (image_id, cave_id, plan_id, file_path, rank, best_id, cloudflare_image_id, cloudflare_thumbnail_id, book_figure, book_page, plan_x_norm, plan_y_norm, subject, description, motifs, medium, photographer, default_priority, hide_plan_xy, thumbnail) VALUES (7568, 22, 22, 'c22/c22a_F1.jpg', 1, NULL, 'b93610a0-64fd-4f1b-2e24-de7d4c0ec300', NULL, NULL, NULL, NULL, NULL, '', '', '', 'photograph', 'Arno Klein', 0, FALSE, NULL) ON CONFLICT (image_id) DO NOTHING;
INSERT INTO images (image_id, cave_id, plan_id, file_path, rank, best_id, cloudflare_image_id, cloudflare_thumbnail_id, book_figure, book_page, plan_x_norm, plan_y_norm, subject, description, motifs, medium, photographer, default_priority, hide_plan_xy, thumbnail) VALUES (7571, 18, 18, 'c18/c18F3.jpg', 1, NULL, '60fa4603-ef64-4b71-0352-7928e1dd6d00', NULL, NULL, NULL, NULL, NULL, '', '', '', 'photograph', 'Arno Klein', 0, FALSE, NULL) ON CONFLICT (image_id) DO NOTHING;
INSERT INTO images (image_id, cave_id, plan_id, file_path, rank, best_id, cloudflare_image_id, cloudflare_thumbnail_id, book_figure, book_page, plan_x_norm, plan_y_norm, subject, description, motifs, medium, photographer, default_priority, hide_plan_xy, thumbnail) VALUES (7572, 18, 18, 'c18/c18F2.jpg', 1, NULL, 'dc75bcea-61b3-4ce4-3897-bc9551d48f00', NULL, NULL, NULL, NULL, NULL, '', '', '', 'photograph', 'Arno Klein', 0, FALSE, NULL) ON CONFLICT (image_id) DO NOTHING;
INSERT INTO images (image_id, cave_id, plan_id, file_path, rank, best_id, cloudflare_image_id, cloudflare_thumbnail_id, book_figure, book_page, plan_x_norm, plan_y_norm, subject, description, motifs, medium, photographer, default_priority, hide_plan_xy, thumbnail) VALUES (7578, 9, 9, 'c9/DSCN4418.jpg', 2, 4376, 'b0222bae-2456-4a40-4abc-b5e85fbc2e00', NULL, NULL, NULL, NULL, NULL, '', '', '', 'photograph', 'Arno Klein', 0, FALSE, NULL) ON CONFLICT (image_id) DO NOTHING;
INSERT INTO images (image_id, cave_id, plan_id, file_path, rank, best_id, cloudflare_image_id, cloudflare_thumbnail_id, book_figure, book_page, plan_x_norm, plan_y_norm, subject, description, motifs, medium, photographer, default_priority, hide_plan_xy, thumbnail) VALUES (7691, 5, 5, 'c5/DSCN4313.jpg', 2, NULL, '950d48fd-65af-4b4b-763a-8f5112ae9700', NULL, NULL, NULL, NULL, NULL, '', '', '', 'photograph', 'Arno Klein', 0, FALSE, NULL) ON CONFLICT (image_id) DO NOTHING;
INSERT INTO images (image_id, cave_id, plan_id, file_path, rank, best_id, cloudflare_image_id, cloudflare_thumbnail_id, book_figure, book_page, plan_x_norm, plan_y_norm, subject, description, motifs, medium, photographer, default_priority, hide_plan_xy, thumbnail) VALUES (7692, 5, 5, 'c5/DSCN4312.jpg', 1, NULL, '7be28853-03db-421f-31e3-b71800836c00', NULL, NULL, NULL, NULL, NULL, '', '', '', 'photograph', 'Arno Klein', 0, FALSE, NULL) ON CONFLICT (image_id) DO NOTHING;
INSERT INTO images (image_id, cave_id, plan_id, file_path, rank, best_id, cloudflare_image_id, cloudflare_thumbnail_id, book_figure, book_page, plan_x_norm, plan_y_norm, subject, description, motifs, medium, photographer, default_priority, hide_plan_xy, thumbnail) VALUES (7690, 5, 5, 'c5/DSCN4314.jpg', 1, NULL, 'c7e588d9-4cd9-4975-2296-275e34663500', NULL, NULL, NULL, NULL, NULL, '', '', '', 'photograph', 'Arno Klein', 0, FALSE, NULL) ON CONFLICT (image_id) DO NOTHING;
INSERT INTO images (image_id, cave_id, plan_id, file_path, rank, best_id, cloudflare_image_id, cloudflare_thumbnail_id, book_figure, book_page, plan_x_norm, plan_y_norm, subject, description, motifs, medium, photographer, default_priority, hide_plan_xy, thumbnail) VALUES (8077, 120, 120, 'c20AB/c20BHl.jpg', 99, NULL, '5115476c-dde4-4865-f505-a0e4dc9bf500', NULL, NULL, NULL, NULL, NULL, '', '', '', 'photograph', 'Arno Klein', 0, FALSE, NULL) ON CONFLICT (image_id) DO NOTHING;

COMMIT;
